// <auto-generated />
namespace RaraAvis.nCubed.CQRS.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Diagnostics;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class CQRS_101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CQRS_101));
        /// <summary>
        /// ID => 201409030918556_CQRS_1.0.1
        /// </summary>
        string IMigrationMetadata.Id
        {
            get { return "201409030918556_CQRS_1.0.1"; }
        }
        /// <summary>
        /// Source
        /// </summary>
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        /// <summary>
        /// Target
        /// </summary>
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
