// <auto-generated />
namespace RaraAvis.nCubed.EventSourcing.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ES_101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ES_101));
        /// <summary>
        /// Id => 201409030935327_ES_1.0.1
        /// </summary>
        string IMigrationMetadata.Id
        {
            get { return "201409030935327_ES_1.0.1"; }
        }
        /// <summary>
        /// Source
        /// </summary>
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        /// <summary>
        /// Target
        /// </summary>
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
